import arrow from './modules/arrow';
import burgerMenu from './modules/burgerMenu';
import calc from './modules/calc';
import dropMenu from './modules/dropMenu';
import gallery from './modules/gallery';
import gift from './modules/gift';
import indexForm from './modules/indexForm';
import menu from './modules/menu';
import modalWindow1 from './modules/modalWindow1';
import modalWindow2 from './modules/modalWindow2';
import promocode from './modules/promocode';
import sendForm3 from './modules/sendForm3';
import sendFormPopUp from './modules/sendFormPopUp';
import slider from './modules/slider';

arrow();
burgerMenu();
calc();
dropMenu();
gallery();
gift();
indexForm();
menu();
modalWindow1();
modalWindow2();
promocode();
sendForm3();
sendFormPopUp();
slider();